# Introduction {-}

<p style="display: block; font-size: 2.25rem; font-weight: 700; color: black; border-bottom: 1px solid #eee; padding-bottom: 10px; margin-top: 24px; margin-bottom: 16px; line-height: 1.25;">
  Introduction
</p>

L’Analyse de la Variance (ANOVA) constitue un outil fondamental en statistique pour étudier l’influence d’un ou plusieurs facteurs sur une variable quantitative. Elle permet de déterminer si les différences observées entre plusieurs groupes sont statistiquement significatives ou simplement dues au hasard.

Dans certaines situations expérimentales, les mesures ne sont pas indépendantes, notamment lorsque plusieurs observations sont réalisées dans un même cadre expérimental ou sur des unités similaires. L’ANOVA permet alors d’analyser simultanément les effets principaux des facteurs étudiés ainsi que leurs interactions éventuelles.

Le présent travail a pour objectif de présenter les fondements théoriques de l’ANOVA, puis d’appliquer ces outils à une base de données expérimentales réelles afin d’identifier les facteurs susceptibles d’influencer la croissance des plantes.

La base mise à disposition porte sur des données réelles
recueillies dans le cadre d’une expérimentation agronomique.

Trois types de terreau ont été étudiés :

* Terreau de Manguier (Ma),

* Terreau de Caïlcédrat (Ca),

* Terreau d’Anacarde (An).

Ces terreaux ont été utilisés sur deux variétés de plantes :

* Variété 1 (Var1),

* Variété 2 (Var2).

L’expérience a été répétée quatre fois et, pour chaque combinaison terreau–variété, la hauteur des plantes a été mesurée.

L’objectif principal de l’étude est de déterminer s’il existe
une association entre le type de terreau et le type de variété qui favorise significativement la croissance des plantes.

Le présent travail s’articule autour de trois parties principales :

* Une première partie consacrée à la présentation synthétique des fondements théoriques de l’Analyse de la Variance ;

* Une deuxième partie dédiée à l’analyse descriptive des variables d’étude et à l’exploration des données ;

* Une troisième partie portant sur l’analyse inferentielle, à travers l’application des modèles ANOVA à un ou deux facteurs (avec ou sans interaction), afin d’identifier les facteurs influençant la croissance des plantes.